React & Redux group project - Space Travelers
fbclh/space-travelers pull request #35
Opened 2022-05-11 21:46 UTC by fbclh

**Project requirements**

- Config & basic setup
- Redux: Fetch data and update Redux store
- Render UI:lists
- Redux: Write actions and reducers for booking rockets and joining missions
- Redux: Write actions and reducers for canceling rockets and leaving missions
- Render UI: conditional components rendering
- Render UI: My Profile section
- Technical set up:
-- Set up the repository on GitHub and use Gitflow.
-- Set up React and Redux.
-- Set up testing libraries(React Testing Library and Jest).
-- Do not preserve user data.

2022-05-11 22:26 UTC, brytebee requested changes
Hi, @fbclh & @sediqullahbadakhsh👋, 

Good job so far!

## Highlights

- The development follows proper Git flow.👏
- The linter files are set up correctly and pass.👏
- Middleware used appropriately.👏
- All tests 🧪 pass.👏
- Snapshot test created and pass.👏
- The app is deployed.👏
- Reservation works correctly.👏
- React / Redux hooks correctly used.👏

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification. 
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-05-11 22:26 UTC, brytebee commented on README.md
- [ ] **Required:** Kindly add the `Testing` section to your readme to specify the procedure for running the tests. This makes your documentation more professional.

2022-05-11 22:26 UTC, brytebee commented on src/pages/ProfilePage.js
> +// import MissionFilter from '../components/Profile/MissionFilter';
- [ ] **Required:** Kindly remove all unused codes from your codebase. It makes code clean, more readable and professional.

2022-05-11 22:26 UTC, brytebee commented on src/pages/ProfilePage.js
> +      {/* <MissionFilter /> */}
- [ ] **Required:** Kindly remove as stated above.

2022-05-11 22:26 UTC, brytebee commented on src/redux/missions/missions.js
> +    //
- [ ] **Required:** Kindly remove. The reason previously explained.

2022-05-12 13:00 UTC, fbclh commented
Hi and thanks, based on your feedback I have made the necessary changes.

- Delete all unnecessary comments.
- Edit README to include test instructions.

2022-05-12 13:09 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi Team,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-12 13:11 UTC, merged